version: '3.7'

services:

  mariadb:
    image: mariadb:11
    container_name: low_auto_erp_mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./.data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: low_auto_erp
      MYSQL_USER: p_nerd
      MYSQL_PASSWORD: 2611
    networks:
      - low_auto_erp_network

  php:
    build:
      context: .
      dockerfile: ./php.dockerfile
    container_name: low_auto_erp_php
    restart: unless-stopped
    volumes:
      - ./server:/var/www/html:cached
      - ./php-fpm.ini:/usr/local/etc/php/conf.d/custom.ini
      - ~/.ssh:/root/.ssh
    depends_on:
      - mariadb
    networks:
      - low_auto_erp_network

  nginx:
    image: nginx:1-alpine
    container_name: low_auto_erp_nginx
    restart: unless-stopped
    ports:
      - 8000:80
      - 443:443
    volumes:
      - ./server:/var/www/html:cached
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl.conf:/etc/nginx/conf.d/ssl/ssl.conf
      - ./cert.pem:/etc/nginx/conf.d/ssl/cert.pem
      - ./cert-key.pem:/etc/nginx/conf.d/ssl/cert-key.pem
    depends_on:
      - php
    networks:
      - low_auto_erp_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: low_auto_erp_phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - mariadb
    networks:
      - low_auto_erp_network

networks:
  low_auto_erp_network:
    driver: bridge

volumes:
  low_auto_erp_volume:
    driver: local
