#!/usr/bin/env zsh

if [[ $1 == "artisan" || $1 == "a" ]]; then
    docker exec law_php php artisan ${*:2}
elif [[ $1 == "postgres" ]]; then
    docker run -e "POSTGRES_PASSWORD=password" -e "POSTGRES_DB=law" -e "POSTGRES_USER=postgres" -p 5432:5432 "postgres:15-alpine" #-v ./postgresql:/var/lib/postgresql/data
fi
